"""LangGraph typed state definitions for the red agent state machine."""

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Any

from langgraph.graph import add_messages
from pydantic import BaseModel, Field


# ── Sub-models ─────────────────────────────────────────────────────────────

class Service(BaseModel):
    """A discovered network service."""
    host: str
    port: int
    protocol: str = "tcp"
    service_name: str = ""
    version: str = ""
    banner: str = ""


class Vulnerability(BaseModel):
    """A potential vulnerability discovered during enumeration."""
    cve_id: str = ""
    cwe_id: str = ""
    title: str = ""
    description: str = ""
    severity: str = ""          # Critical / High / Medium / Low
    cvss_score: float = 0.0
    service: Service | None = None
    confirmed: bool = False     # Set to True only after sandboxed PoC


class ShellSession(BaseModel):
    """A confirmed shell or remote code execution session."""
    host: str
    user: str = ""
    privileged: bool = False
    method: str = ""            # e.g. "CVE-2021-41773" or "SQLi"
    pid: int = 0
    established_at: datetime = Field(default_factory=datetime.now)


class Finding(BaseModel):
    """A single finding tracked throughout the assessment."""
    id: str = ""
    phase: str = ""
    timestamp: datetime = Field(default_factory=datetime.now)
    description: str = ""
    evidence: str = ""          # Raw output or proof
    confidence: float = 0.0     # 0.0–1.0 based on validation status
    vulnerability: Vulnerability | None = None
    remediation: str = ""


class PhaseReport(BaseModel):
    """Summary output from a completed phase."""
    phase: str
    status: str = "incomplete"  # incomplete / complete / failed / skipped
    findings: list[Finding] = []
    summary: str = ""
    next_phase: str = ""


# ── Main Agent State ───────────────────────────────────────────────────────

class AgentState(BaseModel):
    """The full state object flowing through the LangGraph state machine."""

    # Target
    target: str = ""
    target_type: str = ""       # ip / domain / url / cidr

    # Phase tracking
    current_phase: str = "recon"
    phase_history: list[PhaseReport] = []
    phase_retries: int = 0

    # Accumulated findings across all phases
    findings: list[Finding] = []
    services: list[Service] = []
    vulnerabilities: list[Vulnerability] = []
    sessions: list[ShellSession] = []

    # Messages (LangGraph manages this as conversation history)
    messages: Annotated[list, add_messages] = []

    # Intermediate steps stored by the agent during Thought/Action/Observation loops
    intermediate_steps: list[tuple[Any, Any]] = []

    # Agent decision output
    agent_outcome: Any = None

    # Final report
    final_report: str = ""

    # Controls
    done: bool = False
    error: str = ""


class ToolInvocation(BaseModel):
    """A tool call request generated by the LLM."""
    tool: str
    tool_input: dict[str, Any] = Field(default_factory=dict)
